apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: sna
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: sna
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
